name: Release
on:
  release:
    types: [ published ]
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GIT_USER_NAME: sbglasius
      GIT_USER_EMAIL: soeren@glasius.dk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Gradle
        id: cache-gradle
        uses: actions/cache@v2
        with:
          path: ./gradle/
          key: ${{ runner.os }}-gradle
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Set the current release version
        id: release_version
        run: echo ::set-output name=release_version::${GITHUB_REF:11}
      - name: Run pre-release
        uses: micronaut-projects/github-actions/pre-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Sonatype OSSRH
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
          SECRING_FILE: ${{ secrets.SECRING_FILE }}
          SIGNING_PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          echo "$SECRING_FILE" | base64 -d > ${GITHUB_WORKSPACE}/secring.gpg
          echo "Publishing Artifacts"
          set -x
          ./gradlew --info -Prelease=true -Psigning.secretKeyRingFile="${GITHUB_WORKSPACE}/secring.gpg" :external-config:publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon
          set +x
          echo "Publishing Documentation"
      - name: Export Gradle Properties
        uses: micronaut-projects/github-actions/export-gradle-properties@master
      - name: Run post-release
        if: success()
        uses: micronaut-projects/github-actions/post-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
